### ISSUE TITLE
Version clashing when using with react-native-mlkit-ocr

### ISSUE THREAD

**Issue by KevMac19** [yaaliuzhipeng/react-native-mlkit-entity-extraction#1]
Gives error using [react-native-mlkit-entity-extraction](https://github.com/yaaliuzhipeng/react-native-mlkit-entity-extraction) package with [react-native-mlkit-ocr](https://github.com/agoldis/react-native-mlkit-ocr) 

Error is coming while installing pods

OCR package podspec version of GoogleMLKit 

```podspec
s.dependency "GoogleMLKit/TextRecognition", "2.6.0"
```

Entity-extraction package podspec version of GoogleMLKit 

```podspec
s.dependency "GoogleMLKit/EntityExtraction", "2.5.0"
```

**Solution** : Inline this package GoogleMLKit pods version with [react-native-mlkit-ocr](https://github.com/agoldis/react-native-mlkit-ocr) 

@yaaliuzhipeng 
PR - [Updated GoogleMLKit pods version to inline with RN-OCR package](https://github.com/yaaliuzhipeng/react-native-mlkit-entity-extraction/pull/2/files)

**Comment by JasonCareter** [comment]
thanks for contributing

**Comment by JasonCareter** [comment]
> thanks for contributing

already merged
